### ISSUE TITLE
Enable visitor tracking

### ISSUE THREAD

**Issue by dkastl** [dskobe/website#66]
In order to better understand the website users re-enable visitor tracking.

- [ ] Clarify the need for "terms of use" and "privacy policy" pages (en, ja, ??) with laywer
- [ ] Clarify the need for cookie banner implementation with lawyer

Then add visitor tracking code for

- [ ] Google Adwords 
- [ ] Facebook Pixel 

In case cookie banner implementation is required:

- [ ] Implement "Don't track" or "Cookie Banner" 
- [ ] Test and verify the visitors choice is correctly handled
